# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18VMTQvUVZtVgMY_jnr17ERpgjcciHDGX
"""

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,6])
y=np.array([0,250])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([1,2,6,8])
y=np.array([3,8,1,10])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([1,3,5,7,9,11,13,15,17,19,21,23])
y=np.array([2,8,2,8,2,8,2,2,8,2,8,4])

plt.plot(y,marker='o' )
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([3,8,1,11])

plt.plot(y,'o:b' )
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([1,3,5,7,9,11,13,15,17,19,21,23])
y=np.array([2,8,2,8,2,8,2,2,8,2,8,4])

plt.plot(y,marker='o',ms=6)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([1,3,5,7,9,11,13,15,17,19,21,23])
y=np.array([2,8,2,8,2,8,2,2,8,2,8,4])

plt.plot(y,marker='o',ms=29,mec='r' )
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x1=np.array([0,1,2,3])
y1=np.array([3,8,1,10])
x2=np.array([0,1,2,3])
y2=np.array([6,2,7,11])

plt.plot(x1,y1,x2,y2 )
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,1,2,3,4,5])
y=np.array([0,8,12,20,26,38])

plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3,4,5])
y=np.array([0,2,8,1,14,7])
plt.scatter(x,y,color='red')
x=np.array([0,1,2,3,4,5])
y=np.array([3,8,15,30,43,50])
plt.scatter(x,y,color='green')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3,4,5])
y=np.array([0,2,8,1,14,7])
mycolor=['r','g','b','c','m','y']
plt.scatter(x,y,color=mycolor)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3,4,5])
y=np.array([0,2,8,1,14,7])
mycolor=['r','g','b','c','m','y']
size=[10,60,120,80,20,190]
plt.scatter(x,y,color=mycolor,s=size)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['A','B','C','D'])
y=np.array([3,8,1,10])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['A','B','C','D'])
y=np.array([3,8,1,10])
plt.barh(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])

plt.pie(y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
mylabels=["Apples","Bananas","cherries","Dates"]

plt.pie(y,labels=mylabels)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
mylabels=["Apples","Bananas","cherries","Dates"]

plt.pie(y,labels=mylabels,startangle=90)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
mylabels=['SI','Ona tili','ingiliz tili','tarx']
myexplode=[0.2,0,0,0]
plt.pie(y,labels=mylabels,explode=myexplode)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
mylabels=['SI','Ona tili','Fizika','Matematika']
myexplode=[0.2,0,0,0]
plt.pie(y,labels=mylabels,explode=myexplode,shadow=True)
plt.show()